// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Sun Jul 07 00:19:39 2024

speed_sm speed_sm_inst
(
	.speed_sel(speed_sel_sig) ,	// input  speed_sel_sig
	.resetb(resetb_sig) ,	// input  resetb_sig
	.curr_speed(curr_speed_sig) 	// output [2:0] curr_speed_sig
);

defparam speed_sm_inst.state10 = 'b001;
defparam speed_sm_inst.state20 = 'b010;
defparam speed_sm_inst.state30 = 'b011;
defparam speed_sm_inst.state40 = 'b100;
defparam speed_sm_inst.state50 = 'b101;
defparam speed_sm_inst.state60 = 'b110;
